### ISSUE TITLE
_tj singletone is null

### ISSUE THREAD

**Issue by damnedpie** [DrMoriarty/godot-tenjin#2]
Hi, thanks for your work! Been trying to integrate Tenjin via NativeLib addon. However, it seems that singletone can't be found.
```
func _ready() -> void:
	pause_mode = Node.PAUSE_MODE_PROCESS
	if(Engine.has_singleton("Tenjin")):
		print("%s : tenjin initialized" % name)
		_tj = Engine.get_singleton("Tenjin")
	else:
		print("%s : singletone not found" % name)
	var deepLink = ''
	if _facebook != null:
		deepLink = _facebook.deep_link_uri()
	var apiKey = ''
	if ProjectSettings.has_setting('Tenjin/ApiKey'):
		apiKey = ProjectSettings.get_setting('Tenjin/ApiKey')
	init(apiKey, deepLink)
```
This piece (which is basically default tenjin.gd part created upon loading Tenjin via NativeLib) prints "tenjin : singletone not found"

**Comment by damnedpie** [comment]
UPD: I used Python 3.9.9 when I was installing Tenjin. After I have shown NativeCLI other Python version (3.8.5), everything worked and Tenjin has appeared in Godot Android Export Settings in Plugins section.

However it still won't work, logcat just goes in a loop with following trace:
```

07-07 15:54:43.775  1772  3760 I ActivityManager: Process com.onecat.cringethecat (pid 840) has died
07-07 15:54:43.775  1772  3760 D ActivityManager: cleanUpApplicationRecord -- 840
07-07 15:54:43.776  1772  1829 E ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN id=2497, [ Capabilities: NOT_RESTRICTED&TRUSTED&NOT_VPN&FOREGROUND] ]
07-07 15:54:43.777  1772  3760 D ActivityManager: TopActivityInfo, pkgName: com.onecat.cringethecat activityName: com.onecat.cringethecat/com.godot.game.GodotApp callingPackage:   bstSpecialAppKeyboardHandlingEnabled = false
07-07 15:54:43.785   880   880 I art     : Late-enabling -Xcheck:jni
07-07 15:54:43.786   880   880 D houdini : [880] Initialize library(version: 6.1.2d_x.48748 RELEASE)... successfully.
07-07 15:54:43.787   880   880 W art     : Unexpected CPU variant for X86 using defaults: x86
07-07 15:54:43.788  1772  3760 I ActivityManager: Start proc 880:com.onecat.cringethecat/u0a137 for activity com.onecat.cringethecat/com.godot.game.GodotApp
07-07 15:54:43.794  1772  3806 D WindowManager: in computeScreenConfigurationLocked() -- hardKeyboardAvailable :true  mHardKeyboardAvailable :true
07-07 15:54:43.815   880   880 I MultiDex: VM with version 2.1.0 has multidex support
07-07 15:54:43.815   880   880 I MultiDex: Installing application
07-07 15:54:43.815   880   880 I MultiDex: VM has multidex support, MultiDex support library is disabled.
07-07 15:54:43.885   880   880 D WM-WrkMgrInitializer: Initializing WorkManager with default configuration.
07-07 15:54:43.896   880   909 I [myTarget]: start autoinitialization
07-07 15:54:43.897   880   909 I [myTarget]: MyTarget initialization
07-07 15:54:43.917   880   880 V FullScreenGodotApp: Creating new Godot fragment instance.
07-07 15:54:43.921   880   909 D TelephonyManager: creating subscriptionInfo Record, context : androidx.multidex.MultiDexApplication@f9c36dc
07-07 15:54:43.924   880   880 I GodotPluginRegistry: Initializing Godot plugin GodotGooglePlayBilling
07-07 15:54:43.925   880   880 I GodotPluginRegistry: Completed initialization for Godot plugin GodotGooglePlayBilling
07-07 15:54:43.925   880   880 I GodotPluginRegistry: Initializing Godot plugin Tenjin
07-07 15:54:43.927   880   880 D AndroidRuntime: Shutting down VM
07-07 15:54:43.927   880   880 E AndroidRuntime: FATAL EXCEPTION: main
07-07 15:54:43.927   880   880 E AndroidRuntime: Process: com.onecat.cringethecat, PID: 880
07-07 15:54:43.927   880   880 E AndroidRuntime: java.lang.VerifyError: Verifier rejected class ru.mobilap.tenjin.Tenjin: void ru.mobilap.tenjin.Tenjin.<init>(org.godotengine.godot.Godot) failed to verify: void ru.mobilap.tenjin.Tenjin.<init>(org.godotengine.godot.Godot): [0x8] register v2 has type Reference: org.godotengine.godot.Godot but expected Reference: android.app.Activity (declaration of 'ru.mobilap.tenjin.Tenjin' appears in /data/app/com.onecat.cringethecat-2/base.apk:classes5.dex)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at java.lang.Class.classForName(Native Method)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at java.lang.Class.forName(Class.java:400)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at java.lang.Class.forName(Class.java:326)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at org.godotengine.godot.plugin.GodotPluginRegistry.loadPlugins(GodotPluginRegistry.java:140)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at org.godotengine.godot.plugin.GodotPluginRegistry.<init>(GodotPluginRegistry.java:62)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at org.godotengine.godot.plugin.GodotPluginRegistry.initializePluginRegistry(GodotPluginRegistry.java:94)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at org.godotengine.godot.Godot.onCreate(Godot.java:596)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at org.godotengine.godot.FullScreenGodotApp.onCreate(FullScreenGodotApp.java:72)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at com.godot.game.GodotApp.onCreate(GodotApp.java:45)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6785)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1146)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at android.app.ActivityThread.-wrap12(ActivityThread.java)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6138)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
07-07 15:54:43.927   880   880 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
07-07 15:54:43.927   880   880 I Process : Sending signal. PID: 880 SIG: 9
07-07 15:54:43.955  1772  2253 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=2498, [ Capabilities: NOT_RESTRICTED&TRUSTED&NOT_VPN&FOREGROUND] ], android.os.BinderProxy@a41a407)
07-07 15:54:43.955  1772  7966 I ActivityManager: Process com.onecat.cringethecat (pid 880) has died

```

Where com.onecat.cringethecat is the game.

Any advice?
